# Generated by Django 3.1.1 on 2020-10-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about_me', models.TextField(blank=True, max_length=400)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('avatar', models.ImageField(blank=True, default='profile/user.png', upload_to='profile/avatar')),
                ('cover_image', models.ImageField(blank=True, default='profile/bg.jpg', upload_to='profile/cover')),
                ('birthday', models.DateField(blank=True, verbose_name='Date of Birth(Year/Month/Day)')),
                ('cv', models.FileField(blank=True, upload_to='profile/cv')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('skype_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(choices=[('desktop', 'Web Design'), ('file-code', 'Web Development'), ('mobile-android', 'Ui/Ux Design'), ('adversal', 'Advetising'), ('podium-star', 'Motivational Speak'), ('street-view', 'Consultant'), ('game-console-handheld', 'Game Development'), ('microsoft', 'Softwere Development'), ('pencil-paintbrush', 'Graphic design'), ('pencil-alt', 'Story Writing')], max_length=100)),
                ('price', models.CharField(choices=[('desktop', 'Web Design'), ('file-code', 'Web Development'), ('mobile-android', 'Ui/Ux Design'), ('adversal', 'Advetising'), ('podium-star', 'Motivational Speak'), ('street-view', 'Consultant'), ('game-console-handheld', 'Game Development'), ('microsoft', 'Softwere Development'), ('pencil-paintbrush', 'Graphic design'), ('pencil-alt', 'Story Writing')], default='0$-0$', max_length=50)),
                ('details', models.TextField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
