# Generated by Django 3.1.1 on 2020-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(default='0$-0$', max_length=50),
        ),
    ]
