# Generated by Django 3.1.1 on 2020-10-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0002_auto_20201022_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, default='services/cover.jpg', upload_to='services/cover'),
        ),
    ]
