# Generated by Django 3.1.1 on 2020-10-23 01:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0003_service_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(default='2000-2010', max_length=15)),
                ('discription', tinymce.models.HTMLField()),
                ('icon', models.CharField(choices=[('university', 'Education'), ('briefcase', 'Work')], max_length=100)),
                ('label', models.CharField(choices=[('educ', 'Education'), ('workres', 'Work')], max_length=100)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
