# Generated by Django 3.1.1 on 2020-10-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0004_education'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Resume',
        ),
    ]
