# Generated by Django 3.1.1 on 2020-10-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0005_auto_20201023_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='presentation_detail',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='presentation_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
