# Generated by Django 3.1.1 on 2020-10-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0006_auto_20201023_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(upload_to='profile/presentation')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='presentation_detail',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='presentation_video',
        ),
    ]
