# Generated by Django 3.1.1 on 2020-10-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0007_auto_20201023_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
